version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1
    working_directory: ~/wulkanowy
    steps:
      - checkout
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run:
          command: |
            mkdir -p ~/phpunit
            ./vendor/bin/phpunit --log-junit ~/phpunit/junit.xml tests
        when: always
      - run: bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: ~/phpunit
      - store_artifacts:
          path: ~/phpunit
